BugTracker/Models/TicketAttachments.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BugTracker.Models
{
    public class TicketAttachments
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yy, h:mm tt}")]
        public DateTimeOffset Created { get; set; }
        public string UserId { get; set; }
        public string FileUrl { get; set; }
        
        // is this attachment an image?
        public bool IsImage { get; set; }

        public virtual ApplicationUser User { get; set; }
        public virtual Tickets Ticket { get; set; }
    }
}

BugTracker/Models/TicketComments.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Models
{
    public class TicketComments
    {
        public int Id { get; set; }

        [AllowHtml]
        [Required]
        public string Comment { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTimeOffset Created { get; set; }
        public int TicketsId { get; set; }
        public string UserId { get; set; }
        public virtual Tickets Tickets { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

BugTracker/Controllers/TicketCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugTracker.Models;
using Microsoft.AspNet.Identity;

namespace BugTracker.Controllers
{
    [RequireHttps]
    public class TicketCommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TicketComments
        public ActionResult Index()
        {
            var ticketComments = db.TicketComments.Include(t => t.Tickets).Include(t => t.User);
            return View(ticketComments.ToList());
        }

        // GET: TicketComments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketComments ticketComments = db.TicketComments.Find(id);
            if (ticketComments == null)
            {
                return HttpNotFound();
            }
            return View(ticketComments);
        }

        // GET: TicketComments/Create
        public ActionResult Create()
        {
            ViewBag.TicketsId = new SelectList(db.Tickets, "Id", "Title");
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: TicketComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Comment,Created,TicketsId,UserId")] TicketComments ticketComments)
        {
            if (ModelState.IsValid)
            {
                db.TicketComments.Add(ticketComments);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TicketsId = new SelectList(db.Tickets, "Id", "Title", ticketComments.TicketsId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", ticketComments.UserId);
            return View(ticketComments);
        }

        [HttpPost]
        [Authorize]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult LeaveComment(string commentText, int ticketId)
        {
            var helper = new UserRolesHelper();
            var tHelper = new TicketsHelper();
            var userId = User.Identity.GetUserId();

            var user = db.Users.Find(User.Identity.GetUserId());
            var ticket = db.Tickets.Find(ticketId);

            // Check to see if this user meets the criteria to leave a comment
            if (!tHelper.CanEditTicket(user.Id,ticketId) && user.Id != ticket.OwnerUserId)
            {
                return RedirectToAction("Details", "Tickets", new { id = ticketId });
            }

            var comment = new TicketComments();
            comment.Comment = commentText;
            comment.User = user;
            comment.Tickets = ticket;
            comment.Created = DateTimeOffset.Now;
            db.TicketComments.Add(comment);
            db.SaveChanges();

            // notify project manager
            string message = "Comment has been added";
            if (userId != ticket.Project.ManagerId)
            {
                tHelper.CreateNotification(ticketId, ticket.Project.ManagerId, message);
            }

            // notify assigned user
            if (userId != ticket.AssignedUserId && ticket.AssignedUserId != ticket.Project.ManagerId)
            {
                tHelper.CreateNotification(ticketId, ticket.AssignedUserId, message);
            }

            // notify submitter
            if (userId != ticket.OwnerUserId)
            {
                tHelper.CreateNotification(ticketId, ticket.OwnerUserId, message);
            }


            if (User.IsInRole("Admin") || 
                ticket.AssignedUserId == user.Id || 
                (User.IsInRole("Project Manager") && ticket.Project.Users.Contains(user)))
            {
                return RedirectToAction("Edit", "Tickets", new { id = ticketId });
            }
            else
            {
                return RedirectToAction("Details", "Tickets", new { id = ticketId });
            }
            
        }


        // GET: TicketComments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketComments ticketComments = db.TicketComments.Find(id);
            if (ticketComments == null)
            {
                return HttpNotFound();
            }
            ViewBag.TicketsId = new SelectList(db.Tickets, "Id", "Title", ticketComments.TicketsId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", ticketComments.UserId);
            return View(ticketComments);
        }

        // POST: TicketComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Comment,Created,TicketsId,UserId")] TicketComments ticketComments)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticketComments).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TicketsId = new SelectList(db.Tickets, "Id", "Title", ticketComments.TicketsId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", ticketComments.UserId);
            return View(ticketComments);
        }

        // GET: TicketComments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketComments ticketComments = db.TicketComments.Find(id);
            if (ticketComments == null)
            {
                return HttpNotFound();
            }
            return View(ticketComments);
        }

        // POST: TicketComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TicketComments ticketComments = db.TicketComments.Find(id);
            db.TicketComments.Remove(ticketComments);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BugTracker/Views/Shared/_AddUserToProject.cshtml
@using BugTracker.Models;
@model BugTracker.Models.ProjectDetailViewModel

@if (Model.UsersNotInProject != null)
{
    <table class="user-list">
        <tr><th>Action</th><th>User Name</th><th>User Email</th></tr>
        @foreach (var user in Model.UsersNotInProject)
        {
        <tr>
            @*<input type="checkbox" class="cb" id="@user.Id" />*@
            <td>
                <span class="add-user">@Html.ActionLink("Add", "AddUserToProject", new { ProjectId = Model.Project.Id, UserId = user.Id }, new { @class = "addToProject" })</span>
            </td>
            <td>
                @if (user.IsPM() || user.inRole("Demo Project Manager"))
                {
                    <span class="pm">PM</span>
                }
                @if (user.IsDev() || user.inRole("Demo Developer"))
                {
                    <span class="dev">Dev</span>
                }

                @user.Displayname
            </td> 
            <td>
                @user.Email
            </td>
        </tr>

        }
    </table>
}

BugTracker/Views/Shared/_ExternalLoginsListPartial.cshtml
@model BugTracker.Models.ExternalLoginListViewModel
@using Microsoft.Owin.Security

<h4>Use another service to log in.</h4>
<hr />
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0) {
        <div>
            <p>
                There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=403804">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
    }
    else {
        using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = Model.ReturnUrl })) {
            @Html.AntiForgeryToken()
            <div id="socialLoginList">
                <p>
                    @foreach (AuthenticationDescription p in loginProviders) {
                        <button type="submit" class="btn btn-default" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>
                    }
                </p>
            </div>
        }
    }
}

BugTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/PagedList.css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/DataTables/css/jquery.dataTables.min.css")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bug Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Projects", "Index", "Projects")</li>
                    <li>@Html.ActionLink("Tickets", "Index", "Tickets")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Content/DataTables/js/jquery.dataTables.min.js")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BugTracker/Views/Shared/_Login.cshtml
@using BugTracker.Models
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register as a new user", "Register", "Account")
                </p>

                <p>
                    @Html.ActionLink("Forgot your password?", "ForgotPassword", "Account")
                </p>
            }
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm">
            @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BugTracker/Views/Shared/_NotificationsMenuItem.cshtml
@model IList<BugTracker.Models.TicketNotifications>

@if (Model.Count > 0) { 
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"> <i class="ion-ios-bell-outline"></i> <span class="label label-danger">@Model.Count</span></a>
        <ul class="dropdown-menu dropdown-menu-scale lg-dropdown notifications">
            <li> <p>You have @Model.Count new 
                @if (Model.Count > 1)
                {
                    <span>notifications</span> 
                }
                else
                {
                    <span>notification</span> 
                } 
                @*<a href="#"> Mark all Read</a></p></li>*@
            @*<li class="unread-notifications">
                        <a href="#">
                            <i class="ion-ios-email-outline pull-right"></i>
                            <span class="line">You have 8 Messages</span>
                            <span class="small-line">3 Minutes ago</span>
                        </a>
                    </li>
                    <li>
                    <a href="#">
                        <i class="ion-social-twitter-outline pull-right"></i>
                        <span class="line">You have 3 new followers</span>
                        <span class="small-line">8 Minutes ago</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="ion-ios-download-outline pull-right"></i>
                        <span class="line">Download Complete</span>
                        <span class="small-line">6 Minutes ago</span>
                    </a>
                </li>*@
        </ul>
    </li>
}

BugTracker/Views/Shared/_ProjectTickets.cshtml
@model BugTracker.Models.Projects

@if (Model.Tickets.Count > 0) { 
<table id="project-tickets">
    <tr><th>Ticket</th><th>Submitter</th><th>Assigned to</th></tr>
    @foreach (var ticket in Model.Tickets)
    {
        <tr>
            
            <td>@Html.ActionLink(@ticket.Title, "Edit", "Tickets", new { id = @ticket.Id }, null)</td>
            @if (@ticket.OwnerUserId != null) 
            {
                <td>@ticket.OwnerUser.FirstName @ticket.OwnerUser.LastName</td>
            }
            else
            {
                <td>Unknown</td>
            }
            <td>
                @if (@ticket.AssignedUserId != null) 
                {
                    @ticket.AssignedUser.FirstName  @ticket.AssignedUser.LastName
                }
                else
                {
                    <span>Unassigned</span>
                }
            </td>
        </tr>
    }
</table>
}
else
{
    <h4>There are no tickets for this project.</h4>
}

BugTracker/Views/Shared/_TicketAttachments.cshtml
@model BugTracker.Models.Tickets
<section id="ticket-attachments">
    @*<h4>Attachments for this Ticket</h4>*@
    @if (Model.TicketAttachments.Count > 0)
    {
        if (Model.TicketAttachments.Count == 1)
        {
            <p>There is 1 attachment for this ticket</p>
        }
        else
        {
            <p>There are @Model.TicketAttachments.Count attachments for this ticket</p>
        }

        foreach (var attachment in Model.TicketAttachments)
        {
            <div class="ticket-attachment">
                @if (@attachment.IsImage) {
                    <div class="attachment-img"><img src="@attachment.FileUrl" /></div>
                }
                else
                {
                    <div class="attachment-img"><img src="~/Uploads/TxtFile.png" /></div>
                }

                <p><a href="@attachment.FileUrl" target="_top"><span>@attachment.FileUrl</span></a><br /><span>@Html.Raw(@attachment.Description)</span></p>
                <p>Uploaded by <span>@attachment.User.FirstName</span> <span>@attachment.User.LastName on @attachment.Created</span></p>
            </div>
        }
    }
    else
    {
        <h4>No attachments for this ticket</h4>
    }
    <div style="padding-top: 1em">
        <h4>Upload an Attachment</h4>
        @if (ViewBag.CommentAttachmentRights)
        {
            using (Html.BeginForm("UploadTicketAttachment", "Tickets", FormMethod.Post, new { enctype = "Multipart/form-data", novalidate = true }))
            {
                @Html.AntiForgeryToken();
                <input type="hidden" name="ticketId" value="@Model.Id" />
                <span>Description of Attachment[Required]:</span>
                <p><textarea name="description" required></textarea></p>
                <p>Upload a File:</p>
                <input name="attachment" type="file" class="form-control" id="fileUpload" />
                <input type="submit" class="partial-button" value="Upload" />
            }
        }
        else
        {
            <h4 class="alert">Contact Admin or Project Manager for permission to upload ticket attachments.</h4>
        }
    </div>

</section>

BugTracker/Views/Shared/_TicketComments.cshtml
@model BugTracker.Models.Tickets
<section id="ticket-comments">
    @if (Model.TicketComments.Count > 0)
    {
        <h4>Comments for this Ticket</h4>
        foreach (var comment in Model.TicketComments)
        {

            <div class="ticket-comment">
                <p class="ticket-comment-author">
                    @if(comment.User.inRole("Admin") || comment.User.inRole("Demo Admin"))
                    {
                        <span class="admin">Admin</span>
                    }

                    @if (Model.Project.ManagerId == comment.UserId)
                    {
                        <span class="pm">PM</span>
                    }

                    @if (comment.User.IsDev() || comment.User.inRole("Demo Developer"))
                    {
                        <span class="dev">Dev</span>
                    }

                    @if (Model.OwnerUserId == comment.UserId)
                    {
                        <span class="submitter">Submitter</span>
                    }

                    @comment.User.Displayname said:
                </p>
                <p class="ticket-comment-body">@Html.Raw(@comment.Comment)</p>
                <p class="ticket-comment-date">@comment.Created</p>
                <p class="ticket-comment-date"></p>
            </div>
        }
    }
    else
    {
        <h4>No commments for this ticket</h4>
    }
    <div>
        @if (ViewBag.CommentAttachmentRights)
        {
            <span>Leave a comment:</span>
            using (Html.BeginForm("LeaveComment", "TicketComments", FormMethod.Post, new { novalidate = true }))
            {
                @Html.AntiForgeryToken();

            <input type="hidden" name="ticketId" value="@Model.Id" />
            @Html.TextArea("commentText", new { @required = true })
                <div class="row">
                    <div class="col-md-2">
                        <input type="submit" class="partial-button" value="Leave Comment" />
                    </div>
                    
                </div>
            }
        }
        else
        {
            <h4 class="alert">Contact Admin or Project Manager for permission to leave comments.</h4>
        }
    </div>
</section>

BugTracker/Views/Shared/_TicketHistory.cshtml
@model BugTracker.Models.Tickets
<section id="ticket-comments">
    <h4>History of this Ticket</h4>
    @if (Model.TicketHistories.Count > 0)
    {
        <table id="ticket-history">
            <thead>
                <tr><th>Date</th><th>User</th><th>Property</th><th>Old Value</th><th>New Value</th></tr>
            </thead>
            <tbody>
                @foreach (var item in Model.TicketHistories)
                {
                    <tr>
                        <td>@item.ChangedDate</td>
                        <td>@item.User.Displayname</td>
                        <td>@item.Property</td>
                        <td class="old">@Html.Raw(@item.ToMessage(true))</td>
                        <td class="new">@Html.Raw(@item.ToMessage(false))</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h4>No changes on this ticket</h4>
    }

</section>

BugTracker/Views/Shared/_TicketNav.cshtml
<p class="ticket-nav">
    @Html.ActionLink("All Tickets","Index")

    @if (User.IsInRole("Submitter"))
    {
        @Html.ActionLink("Create New", "Create")

        @Html.ActionLink("My Submitted Tickets", "SubmittedTickets")
    }

    @if (User.IsInRole("Project Manager") || User.IsInRole("Developer"))
    {
        @Html.ActionLink("My Assigned Tickets", "AssignedTickets")
    }

    @if (User.IsInRole("Project Manager"))
    {
        @Html.ActionLink("Tickets for My Projects", "ProjectTickets")
    }

    @*@using (Html.BeginForm()) {
            @Html.AntiForgeryToken();
            @Html.Label("Search")
            <span>&nbsp;</span>
            @Html.TextBox("searchStr")
            <input type="submit" value="Go" />
        }*@
</p>

BugTracker/Views/Shared/_TicketUsers.cshtml
@model BugTracker.Models.Tickets
<section id="ticket-users">

    @if (Model.AssignedUser == null)
    {
        <h4>Assign a user to this ticket</h4>
        <table class="user-list">
            <tr><th>Role(s)</th><th>Name</th><th>Display Name</th><th>Email</th><th>Action</th></tr>
            @foreach (var user in Model.Project.Users)
            {
                <tr>
                    <td>
                        @if (user.IsPM() || user.inRole("Demo Project Manager"))
                    {
                            <span class="pm">PM</span>
                        }
                        @if (user.IsDev() || user.inRole("Demo Developer"))
                    {
                            <span class="dev">Dev</span>
                        }
                    </td>
                    <td>@user.FirstName @user.LastName</td>
                    <td>@user.Displayname</td>
                    <td>@user.Email</td>
                    <td><span class="add-user">@Html.ActionLink("Assign", "AssignUserToTicket", new { TicketId = Model.Id, UserId = @user.Id })</span></td>
                </tr>
            }
        </table>
    }
    else
    {
        @Html.LabelFor(model => model.AssignedUserId, "Assigned User", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Label(Model.AssignedUser.Displayname, htmlAttributes: new { @class = "control-label" })
            <span class="remove-manager">@Html.ActionLink(" X", "RemoveAssignedUserFromTicket", new { ticketId = Model.Id })</span>
        </div>
    }

</section>

BugTracker/Views/Shared/_UserRoles.cshtml
@model IEnumerable<BugTracker.Models.ProjectUsers>


@foreach (var item in Model)
{
    <p>@item.User.Email</p>
}

BugTracker/Views/Shared/_UsersInProject.cshtml
@using BugTracker.Models;
@model ProjectDetailViewModel


@*@foreach (var user in Model.Users)
    {
        <div class="user-search">

            @Html.ActionLink("Add", "AddUserToProject", new {ProjectId = Model.ProjectId, UserId = user.Id }, new { @class="addToProject" })
            @user.FirstName @user.LastName | @user.Displayname | @user.Email
        </div>
    }*@

<h2>Users Assigned to this Project</h2>
<table class="user-list">
    <tr><th>Role(s)</th><th>Name</th><th>Display Name</th><th>Email</th><th>Remove</th></tr>
    @if (Model.Project.ManagerId != null)
    {
        <tr>
            <td>
                @if (Model.Manager.IsPM() || Model.Manager.inRole("Demo Project Manager"))
                {
                    <span class="pm">PM</span>
                }
                @if (Model.Manager.IsDev() || Model.Manager.inRole("Demo Developer"))
                {
                    <span class="dev">Dev</span>
                }
            </td>
            <td>
                @Model.Manager.FirstName @Model.Manager.LastName
            </td>
            <td>
                @Model.Manager.Displayname
            </td>
            <td>
                @Model.Manager.Email
            </td>
            <td>
                
            </td>
       </tr>
    }
    @foreach (var user in Model.Project.Users.Where(u => u.Id != Model.Project.ManagerId))
    {
        <tr>
            <td>
                @*@if (user.IsPM())
                {
                    <span class="pm">PM</span>
                }*@
                @if (user.IsDev() || user.inRole("Demo Developer"))
                {
                    <span class="dev">Dev</span>
                }
            </td>
            <td>@user.FirstName @user.LastName</td>
            <td>@user.Displayname</td>
            <td>@user.Email</td>
            <td><span class="remove-manager">@Html.ActionLink("X", "RemoveProjectUser", new { ProjectId = Model.Project.Id, UserId = @user.Id }, new { @class = "removeFromProject" })</span></td>
        </tr>
    }
</table>